_core:
  default_config_hash: QUZHrnAKd4ixgLLVtD3JrrBMlwbmJ6VU-qKcOMDKatw
buttons_size: 32
additional_html: "    <span class=\"wrap-icon\">    <i class=\"fa-solid fa-share-nodes\"></i> <span class=\"wrap-text\">Share</span> </span>\r\n<span class=\"wrap-btn\">\r\n<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_pinterest\"></a>\r\n<a class=\"a2a_button_telegram\"></a>\r\n</span>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 1
  node: 1
  comment: 1
  block_content: 0
  contact_message: 0
  file: 0
  menu_link_content: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  paragraph: 0
