_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -45
    expanded: false
    enabled: false
  contact__site_page:
    weight: -46
    menu_name: footer
    parent: ''
    expanded: false
    enabled: false
