_core:
  default_config_hash: TgDhjkaZTZ249_U2CFEd--I4RLMZDmPWSO8pmr3odzw
entity_types:
  block_content: block_content
  media: media
  menu_link_content: menu_link_content
  node: node
  taxonomy_term: taxonomy_term
  user: user
  comment: 0
  shortcut: 0
