<?php

use Drupal\Core\Form\FormStateInterface;

function green_view_filter_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $vocabulary_id = 'tags';
// Get this from your view object's contextual argument, e.g. $view->args[0], etc
  $parent_id = 11;

  $child_terms = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->loadTree($vocabulary_id, $parent_id);

// Next build an options array of the child terms.
  $child_term_options = [];
// Maybe you want an Any option
  foreach ($child_terms as $term) {
    $child_term_options[$term->tid] = $term->name;
  }

// Next update your filter options with only the child terms:
  $form['dont_miss_filter']['#options'] = $child_term_options;
}
